### ISSUE TITLE
Modeling `Type\Author` for h-feed.

### ISSUE THREAD

**Issue by mblaney** [simplepie/simplepie-ng#22]
this looks awesome @skyzyx! Glad you've got the time to take this on.

Just wanted to mention an issue I've had when retrofitting microformats into SimplePie OG (yes I think I will use that term...) The issue is that h-entry's have a wider vocabulary for authors via h-card than traditional feeds. So instead of just being a name or email address they can be full html markup with profile images, urls, etc. This makes it hard to be an afterthought because you've probably made a few assumptions about content types for author before implementing it.

Anyway feel free to close this issue.

**Comment by skyzyx** [comment]
No, this is solid feedback. I've already started modeling what an `Author` is, and all of these models have the flexibility to grow. JSON Feed supports name, email, and profile image. Atom(s) and RSS(s) have their own variances.

In short, some of these will be populated, and some will not. That's the best way I can think of to handle things like this.

**Comment by skyzyx** [comment]
I think this is done, even though h-author support specifically hasn't been added.
